### ISSUE TITLE
老哥有没有想过这个Umi如何支持并发请求，Umi的http请求是单线程的

### ISSUE THREAD

**Issue by zhangzijie666** [iszmxw/ocr#12]

**Comment by iszmxw** [comment]
没研究过，但是这个软件的本质还是套壳
你可从根本上研究来解决，我看原作者也是使用者两个库
- [x] 【[RapidOcrOnnx](https://github.com/RapidAI/RapidOcrOnnx)】
- [x] 【[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)】
其他的库也可以集成进来，但是我对 `C++` 不是很熟

原则上编译成可执行文件打包成服务可供其他语言调用，利用你熟悉的语言来编写通用 `api` 接口封装成 `sdk`

我之前想过要是编译成常用的`amd64` 环境可运行的 再用 `golang` 封装对接效率肯定会不错，不过目前没什么时间，你有兴趣的话可以往这方面研究研究

**Comment by zhangzijie666** [comment]
感谢您的回答，让我有节省了找解决方案的时间，思路一下就清晰了
