### ISSUE TITLE
拉取镜像失败

### ISSUE THREAD

**Issue by zhangwanshen** [iszmxw/ocr#13]
(base) [root@app-docker2 umi_ocr]# docker pull --platform linux/amd64 iszmxw/ocr:3.1
3.1: Pulling from iszmxw/ocr
96d54c3075c9: Retrying in 4 seconds
1db0bfccf166: Retrying in 4 seconds
4cd5305fa16f: Retrying in 4 seconds
ff2202daa1a3: Waiting
error pulling image configuration: download failed after attempts=6: dial tcp 66.220.149.32:443: connect: connection timed out
然后我pin了一下网络也没问题
(base) [root@app-docker2 umi_ocr]# ping docker.io
PING docker.io (44.193.181.103) 56(84) bytes of data.

**Comment by iszmxw** [comment]
你用的是国内的还是国外的服务器

**Comment by iszmxw** [comment]
![image](https://github.com/iszmxw/ocr-docker/assets/31272102/d440cffb-459d-49c5-b08d-b7ae08a290ff)

**Comment by zhangwanshen** [comment]
我用的是国内的服务器，腾讯云租的云服务
[root@VM-0-14-centos ~]# docker pull --platform linux/amd64 iszmxw/ocr:3.1
3.1: Pulling from iszmxw/ocr
96d54c3075c9: Retrying in 1 second 
1db0bfccf166: Retrying in 1 second 
4cd5305fa16f: Retrying in 1 second 
ff2202daa1a3: Waiting 
error pulling image configuration: download failed after attempts=6: dial tcp 31.13.80.54:443: i/o timeout
有什么方式手动下载吗？或者还有什么其他方式可以在Linux调用ocr接口吗？

**Comment by iszmxw** [comment]
国内厂商已经把 `docker` 给墙了,你可以网上找一下镜像看看
