### ISSUE TITLE
老哥，怎样往里更新版本呢，我看你这个用户什么权限都没开，没法复制文件

### ISSUE THREAD

**Issue by Mingxiangyu** [iszmxw/ocr#4]

**Comment by iszmxw** [comment]
可以使用 `root` 用户，密码是一样的

**Comment by Mingxiangyu** [comment]
> 可以使用 `root` 用户，密码是一样的

嗯嗯，已经用docker cp实现了，感谢老哥，哎，但是还是实现不了文档的识别操作

**Comment by iszmxw** [comment]
> > 可以使用 `root` 用户，密码是一样的
> 
> 嗯嗯，已经用docker cp实现了，感谢老哥，哎，但是还是实现不了文档的识别操作

不知道你要识别什么文档，一般都是识别截图

**Comment by Mingxiangyu** [comment]
> > > 可以使用 `root` 用户，密码是一样的
> > 
> > 
> > 嗯嗯，已经用docker cp实现了，感谢老哥，哎，但是还是实现不了文档的识别操作
> 
> 不知道你要识别什么文档，一般都是识别截图

大佬的最新测试版本2.1.0已经能实现识别pdf了，但是我cp到容器中却没法启动

**Comment by iszmxw** [comment]
> > > > 可以使用 `root` 用户，密码是一样的
> > > 
> > > 
> > > 嗯嗯，已经用docker cp实现了，感谢老哥，哎，但是还是实现不了文档的识别操作
> > 
> > 
> > 不知道你要识别什么文档，一般都是识别截图
> 
> 大佬的最新测试版本2.1.0已经能实现识别pdf了，但是我cp到容器中却没法启动

- 已打包 `Umi-OCR_Rapid_v2.1.1.7z.exe`版本

- 引用地址 [https://github.com/hiroi-sora/Umi-OCR/releases](https://github.com/hiroi-sora/Umi-OCR/releases)

- 容器版本 `iszmxw/ocr:3.1` ,里面包含了 `Rapid_2.0.0` 和 `Rapid_2.1.1` 版本

![图1](https://github.com/iszmxw/ocr-docker/assets/31272102/a2c73355-11db-41be-8dfd-f735b1a82f3e)

![图2](https://github.com/iszmxw/ocr-docker/assets/31272102/b023477d-befb-4f34-a264-fd523adefa58)

**Comment by Mingxiangyu** [comment]
强，给大佬点赞
