### ISSUE TITLE
使用新版本，运行报错

### ISSUE THREAD

**Issue by yancccc** [iszmxw/ocr#5]
??????,??????
0108:fixme:nls:get_dummy_preferred_ui_language (0x8 0x409 000000000011E660 000000000011E5B0 000000000011E668) returning a dummy value (current locale)
0108:fixme:nls:get_dummy_preferred_ui_language (0x8 0x409 000000000011E430 000000000011E380 000000000011E438) returning a dummy value (current locale)
qml: % ??????????! ThemeManager_QMLTYPE_0(0xd697ee0)
qml: ui.i18n ???? zh_CN
qml: ui.opengl ???? AA_UseOpenGLES
qml: developer.textScale ???? 1
qml: ui.fontBtn ????UI?undefined
qml: ocr.btns ????UI?undefined
0108:fixme:dxgi:dxgi_resource_GetSharedHandle iface 00000000002EA158, shared_handle 000000000DB1D080 stub!
0108:fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 12.0.0, 256 bits)").
0108:fixme:dwmapi:DwmEnableBlurBehindWindow 000000000002007C 000000000010E3D0
0108:fixme:dxgi:wined3d_swapchain_desc_from_dxgi Ignoring alpha mode 0.
0108:fixme:dxgi:wined3d_bind_flags_from_dxgi_usage Unhandled DXGI usage 0x40.
0108:fixme:systray:Shell_NotifyIconGetRect stub (000000000011AFC0) (000000000011AFB0)
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (XFree86-VidModeExtension)
  Minor opcode of failed request:  15 (XF86VidModeSetGamma)
  Value in failed request:  0x3600174
  Serial number of failed request:  1494
  Current serial number in output stream:  1502

**Comment by iszmxw** [comment]
> ??????,?????? 0108:fixme:nls:get_dummy_preferred_ui_language (0x8 0x409 000000000011E660 000000000011E5B0 000000000011E668) returning a dummy value (current locale) 0108:fixme:nls:get_dummy_preferred_ui_language (0x8 0x409 000000000011E430 000000000011E380 000000000011E438) returning a dummy value (current locale) qml: % ??????????! ThemeManager_QMLTYPE_0(0xd697ee0) qml: ui.i18n ???? zh_CN qml: ui.opengl ???? AA_UseOpenGLES qml: developer.textScale ???? 1 qml: ui.fontBtn ????UI?undefined qml: ocr.btns ????UI?undefined 0108:fixme:dxgi:dxgi_resource_GetSharedHandle iface 00000000002EA158, shared_handle 000000000DB1D080 stub! 0108:fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 12.0.0, 256 bits)"). 0108:fixme:dwmapi:DwmEnableBlurBehindWindow 000000000002007C 000000000010E3D0 0108:fixme:dxgi:wined3d_swapchain_desc_from_dxgi Ignoring alpha mode 0. 0108:fixme:dxgi:wined3d_bind_flags_from_dxgi_usage Unhandled DXGI usage 0x40. 0108:fixme:systray:Shell_NotifyIconGetRect stub (000000000011AFC0) (000000000011AFB0) X Error of failed request: BadValue (integer parameter out of range for operation) Major opcode of failed request: 151 (XFree86-VidModeExtension) Minor opcode of failed request: 15 (XF86VidModeSetGamma) Value in failed request: 0x3600174 Serial number of failed request: 1494 Current serial number in output stream: 1502

使用的是那个版本

**Comment by yancccc** [comment]
Umi-OCR_Paddle_v2.1.0

**Comment by iszmxw** [comment]
> Umi-OCR_Paddle_v2.1.0

- 已打包 `Umi-OCR_Rapid_v2.1.1.7z.exe`版本

- 引用地址 [https://github.com/hiroi-sora/Umi-OCR/releases](https://github.com/hiroi-sora/Umi-OCR/releases)

- 容器版本 `iszmxw/ocr:3.1` ,里面包含了 `Rapid_2.0.0` 和 `Rapid_2.1.1` 版本

![图1](https://github.com/iszmxw/ocr-docker/assets/31272102/a2c73355-11db-41be-8dfd-f735b1a82f3e)

![图2](https://github.com/iszmxw/ocr-docker/assets/31272102/b023477d-befb-4f34-a264-fd523adefa58)
