### ISSUE TITLE
远程访问报错

### ISSUE THREAD

**Issue by yancccc** [iszmxw/ocr#6]
![image](https://github.com/iszmxw/ocr-docker/assets/26217359/a6bd53bf-af83-404f-9a5d-4cc2bcb6b9b2)
{
    "code": 301,
    "data": "Base64 data imdecode failed.",
    "time": 0.03252911567687988,
    "timestamp": 1710833872.8054676
}

**Comment by yancccc** [comment]
小的图片可以运行，大的图片就报这个错误，老哥能不能看下什么原因

**Comment by iszmxw** [comment]
> 小的图片可以运行，大的图片就报这个错误，老哥能不能看下什么原因

本地电脑可以运行解析大图吗

**Comment by yancccc** [comment]
本地可以

**Comment by yancccc** [comment]
![image](https://github.com/iszmxw/ocr-docker/assets/26217359/4d73c186-74ef-4d00-ad76-91d4e5133490)
![image](https://github.com/iszmxw/ocr-docker/assets/26217359/f5c977d8-63fd-4c80-9261-905bd318dfda)

**Comment by yancccc** [comment]
![image](https://github.com/iszmxw/ocr-docker/assets/26217359/03ef4f02-2d53-4ce7-9cfc-84329a46f1fb)
![image](https://github.com/iszmxw/ocr-docker/assets/26217359/45d8dc7b-0986-4675-a6e6-f597c1cad8d0)
好像是换行就会出问题

**Comment by yancccc** [comment]
![image](https://github.com/iszmxw/ocr-docker/assets/26217359/bfe91217-002b-4d7b-9a98-841e390becad)

**Comment by iszmxw** [comment]
> ![image](https://private-user-images.githubusercontent.com/26217359/315216468-bfe91217-002b-4d7b-9a98-841e390becad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjExMTEsIm5iZiI6MTcxNTE2MDgxMSwicGF0aCI6Ii8yNjIxNzM1OS8zMTUyMTY0NjgtYmZlOTEyMTctMDAyYi00ZDdiLTlhOTgtODQxZTM5MGJlY2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5MzMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NjY3ZTE4ZTBiOGE2ZDc2Yzc2MDQwOTc5MmZjZmE4Y2RkN2ZjNzYwYmM2MzVhNDcwMDMzZjU1ZmU1YWZlYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zPU3qdr6OSRKzw4nuBHfErsPjBdJn0DbvGAPiczwcp0)

这个就不清楚了，程序报的错误，可能是兼容性问题

- 已打包 `Umi-OCR_Rapid_v2.1.1.7z.exe`版本

- 引用地址 [https://github.com/hiroi-sora/Umi-OCR/releases](https://github.com/hiroi-sora/Umi-OCR/releases)

- 容器版本 `iszmxw/ocr:3.1` ,里面包含了 `Rapid_2.0.0` 和 `Rapid_2.1.1` 版本

![图1](https://github.com/iszmxw/ocr-docker/assets/31272102/a2c73355-11db-41be-8dfd-f735b1a82f3e)

![图2](https://github.com/iszmxw/ocr-docker/assets/31272102/b023477d-befb-4f34-a264-fd523adefa58)
