### ISSUE TITLE
api请求出错

### ISSUE THREAD

**Issue by Yejnf** [iszmxw/ocr#7]
<img width="643" alt="屏幕截图 2024-05-04 001030" src="https://github.com/iszmxw/ocr-docker/assets/103319984/43ca043e-3291-468f-b52e-7d99ad29b4d2">
<img width="620" alt="屏幕截图 2024-05-04 001105" src="https://github.com/iszmxw/ocr-docker/assets/103319984/5690acd6-4ab9-48f5-875d-c7d7db3ae727">

api请求出错

**Comment by iszmxw** [comment]
这个是软件报的错误吧

**Comment by shaoxinghua0623** [comment]
@Yejnf 大佬，你解决这个问题了吗？
