### ISSUE TITLE
老哥，有没有尝试过再打包一版新版本umi呢

### ISSUE THREAD

**Issue by Mingxiangyu** [iszmxw/ocr#8]

**Comment by iszmxw** [comment]
- 已打包 `Umi-OCR_Rapid_v2.1.1.7z.exe`版本

- 引用地址 [https://github.com/hiroi-sora/Umi-OCR/releases](https://github.com/hiroi-sora/Umi-OCR/releases)

- 容器版本 `iszmxw/ocr:3.1` ,里面包含了 `Rapid_2.0.0` 和 `Rapid_2.1.1` 版本

![图1](https://github.com/iszmxw/ocr-docker/assets/31272102/a2c73355-11db-41be-8dfd-f735b1a82f3e)

![图2](https://github.com/iszmxw/ocr-docker/assets/31272102/b023477d-befb-4f34-a264-fd523adefa58)
