### ISSUE TITLE
老哥帮忙看一下吧！部署后ip加端口号访问不通，版本号显示

### ISSUE THREAD

**Issue by zhangzijie666** [iszmxw/ocr#9]
![7acfdc775329afd3e49014f02581768](https://github.com/iszmxw/ocr-docker/assets/166745907/194fb2ea-dc00-45a6-b9d5-69d170e3a134)

**Comment by zhangzijie666** [comment]
![Uploading 580a7532a913ba549e9e803f221029a.png…]()

**Comment by zhangzijie666** [comment]
![580a7532a913ba549e9e803f221029a](https://github.com/iszmxw/ocr-docker/assets/166745907/11c2bac3-64fa-4841-a7e6-ffd08773cc76)
这个是ocr已经打开了的截图

**Comment by iszmxw** [comment]
服务器的防火墙端口没有打开吧，阿里云或者腾讯云放开端口再试试
